name = "kunpengzhi-podcast"
main = "src/index.ts"
compatibility_date = "2026-09-13"

[build]
command = "bun run build || npm run build"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "kunpengzhi-counters"
database_id = "kunpengzhi-counters"


