#!/usr/bin/env python3
"""Generate a self-contained SVG preview from the local Neo4j graph."""
import html, json, math, os, urllib.request

ENDPOINT = os.environ.get("NEO4J_ENDPOINT", "http://127.0.0.1:7474/db/neo4j/tx/commit")
OUT = os.path.join(os.path.dirname(__file__), "neo4j-graph-preview.svg")

def cypher(statement):
    body = json.dumps({"statements": [{"statement": statement}] }).encode()
    req = urllib.request.Request(ENDPOINT, data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=20) as response:
        payload = json.load(response)
    if payload.get("errors"):
        raise RuntimeError(payload["errors"])
    result = payload["results"][0]
    cols = result["columns"]
    return [dict(zip(cols, row["row"])) for row in result["data"]]

def esc(value):
    return html.escape(str(value or ""), quote=True)

nodes = cypher("MATCH (n) RETURN count(n) AS nodes")[0]["nodes"]
rels = cypher("MATCH ()-[r]->() RETURN count(r) AS rels")[0]["rels"]
edges = cypher("""
MATCH (a:Agent)-[r]-(b)
RETURN elementId(a) AS aid, coalesce(a.name, a.id, 'Agent') AS aname,
       type(r) AS rel, elementId(b) AS bid,
       coalesce(b.name, b.title, head(labels(b)), 'node') AS bname
LIMIT 80
""")

agents, related = [], []
agent_ids, related_ids = set(), set()
for e in edges:
    if e["aid"] not in agent_ids:
        agent_ids.add(e["aid"]); agents.append((e["aid"], e["aname"]))
    if e["bid"] not in related_ids:
        related_ids.add(e["bid"]); related.append((e["bid"], e["bname"]))

W, H = 1600, 980
left_x, right_x = 310, 1080
def positions(items, x):
    if not items: return {}
    gap = min(92, (H - 170) / max(1, len(items)))
    start = 125
    return {key: (x, start + i * gap) for i, (key, _) in enumerate(items)}
apos, rpos = positions(agents, left_x), positions(related, right_x)
lines = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">',
         '<defs><linearGradient id="bg" x2="0" y2="1"><stop stop-color="#111827"/><stop offset="1" stop-color="#020617"/></linearGradient><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs>',
         '<rect width="100%" height="100%" fill="url(#bg)"/>',
         '<text x="70" y="70" fill="#f8fafc" font-size="30" font-family="sans-serif" font-weight="700">鲲鹏志 · Neo4j Graph Preview</text>',
         f'<text x="70" y="108" fill="#94a3b8" font-size="17" font-family="sans-serif">主实例真实数据：{nodes:,} nodes · {rels:,} relationships · Agent 邻接抽样 80 条</text>',
         '<text x="310" y="145" text-anchor="middle" fill="#60a5fa" font-size="19" font-family="sans-serif">Agent</text>',
         '<text x="1080" y="145" text-anchor="middle" fill="#fb923c" font-size="19" font-family="sans-serif">Connected entity / label</text>']
for e in edges:
    x1, y1 = apos[e["aid"]]; x2, y2 = rpos[e["bid"]]
    lines.append(f'<line x1="{x1+18}" y1="{y1}" x2="{x2-18}" y2="{y2}" stroke="#475569" stroke-width="1.5" opacity=".68" marker-end="url(#arrow)"/>')
    mx, my = (x1+x2)/2, (y1+y2)/2
    lines.append(f'<text x="{mx:.1f}" y="{my-3:.1f}" text-anchor="middle" fill="#94a3b8" font-size="11" font-family="sans-serif">{esc(e["rel"])}</text>')
for key, label in agents:
    x, y = apos[key]
    lines += [f'<circle cx="{x}" cy="{y}" r="19" fill="#2563eb" stroke="#93c5fd" stroke-width="2"/>', f'<text x="{x-30}" y="{y+5}" text-anchor="end" fill="#dbeafe" font-size="14" font-family="sans-serif">{esc(label)}</text>']
for key, label in related:
    x, y = rpos[key]
    lines += [f'<circle cx="{x}" cy="{y}" r="19" fill="#c2410c" stroke="#fdba74" stroke-width="2"/>', f'<text x="{x+30}" y="{y+5}" fill="#ffedd5" font-size="14" font-family="sans-serif">{esc(label)}</text>']
lines.append('<text x="70" y="940" fill="#64748b" font-size="13" font-family="sans-serif">Generated by tests/generate_neo4j_svg.py · static preview, no credentials embedded</text></svg>')
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} ({len(edges)} edges, {len(agents)} agents, {len(related)} related nodes)")
